
# DIMENSIONS
TILE_SIZE = 64  # tiles are square height==width
SCREEN_WIDTH = 12 * TILE_SIZE
SCREEN_HEIGHT = 8 * TILE_SIZE
SAND_HEIGHT = 20

# COLORS
WATER_COLOR = (0, 159, 232)
SAND_COLOR = (100, 25, 0)